### ISSUE TITLE
Multithreading Problem

### ISSUE THREAD

**Issue by 253153** [splitice/QuadTrees#12]
We are building a real time mmo "io game" using this library for collision checking, and the "websocketsharp" library for websocket connections.

We are running into the following problem sometimes when objects are being inserted:

```
We are not the root, and this object doesn't fit here. How did we get here?
   at QuadTrees.Common.QuadTreeFNodeCommon`3.Insert(QuadTreeObject`2 item, Boolean canSubdivide) in /root/GS2/QuadTrees/Common/QuadTreeFNodeCommon.cs:line 846
   at QuadTrees.Common.QuadTreeFCommon`3.Add(TObject item) in /root/GS2/QuadTrees/Common/QuadTreeFCommon.cs:line 162
   at GS2.Server.AddGameObject(GameObject gameObject) in /root/GS2/Server.cs:line 490
   at GS2.Player.Attack() in /root/GS2/Player.cs:line 383
   at GS2.Server.ProcessMessageQueue() in /root/GS2/Server.cs:line 280
   at GS2.Server.update() in /root/GS2/Server.cs:line 165
   at GS2.Server.TimerLoop() in /root/GS2/Server.cs:line 147
   at GS2.Server.StartServer() in /root/GS2/Server.cs:line 103
   at GS2.Program.Main(String[] args) in /root/GS2/Program.cs:line 22
```

I understand this issue is likely occurring due to multithreading issues,  and have tried locking the Quadtree like so when adding but it did not fix the issue:

```
                lock (QuadTree)
                {
                    if (!QuadTree.Contains(gameObject.Hitbox))
                    {
                        QuadTree.Add(gameObject.Hitbox);
                    }
                }
```

Could anyone please recommend a way to fix this issue?

**Comment by splitice** [comment]
Take a lock before using the structure as you would with any dictionary or similar structure. You are missing your lock somewhere.

Also although it's fine with this library it's generally bad form to lock arbitary objects. Good practice is to create an object for locking purposes.
